image: node:18

cache:
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm run test:coverage  # Run tests with coverage
  artifacts:
    paths:
      - coverage/  # Save coverage reports as artifacts
    expire_in: 1 week
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  only:
    - merge_requests
    - branches  # Runs on all branches
